all: UP000464024.fasta

UP000464024.fasta:
	wget --no-check-certificate --auth-no-challenge --output-document=UP000464024.fasta "https://www.uniprot.org/uniprot/?query=proteome:UP000464024&format=fasta"

clean:
	rm *.png *.latex *.csv *.pdf *.fasta




