all: non-TMH-Bcell-elution.txt TMH-Bcell-elution.txt UP000005640_9606.fasta.gz

UP000005640_9606.fasta.gz:
	wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/Eukaryota/UP000005640_9606.fasta.gz

non-TMH-Bcell-elution.txt:
	wget https://github.com/richelbilderbeek/bianchi_et_al_2017/raw/master/data/non-TMH-Bcell-elution.txt

TMH-Bcell-elution.txt:
	wget https://github.com/richelbilderbeek/bianchi_et_al_2017/raw/master/data/TMH-Bcell-elution.txt
