all: non-TMH-Bcell-elution.txt TMH-Bcell-elution.txt


non-TMH-Bcell-elution.txt:
	wget https://github.com/richelbilderbeek/bianchi_et_al_2017/raw/master/data/non-TMH-Bcell-elution.txt

TMH-Bcell-elution.txt:
	wget https://github.com/richelbilderbeek/bianchi_et_al_2017/raw/master/data/TMH-Bcell-elution.txt
