# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: Build LaTeX document

jobs:
  build_latex:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Latex compiler
        uses: Jatus93/Latex-multicompiler@master
        with:
          path_to_list: bbbq_header.tex

      #- name: latex2pdf
      #  uses: thomas-chauvet/latex2pdf-action@1.0.1
      #  with:
      #    main_latex_file: bbbq_header.tex
      #    ctan_packages: amssymb latexsym amsmath

      #- name: Compile LaTeX document
      #  uses: dante-ev/latex-action@latest
      #  with:
      #    root_file: bbbq_header.tex

      #- name: Compile LaTeX document
      #  uses: xu-cheng/latex-action@v2
      #  with:
      #    root_file: bbbq_header.tex

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: my-pdf
          path: bbbq_article.pdf

